
#固有テク
UniqTechList = [
	['CIVILIZATION_ENGLAND', ['TECH_KOUMAKAN', 'TECH_GOKUSAINODANMAKU', 'TECH_JIKANSOUSA', 'TECH_SICHIYOUNOMAJUTU', 'TECH_UNMEISOUSA', 'TECH_QED', 'TECH_AKAIKIRI'] ], 
	['CIVILIZATION_FRANCE', ['TECH_HAKUGYOKUROU', 'TECH_NEKOMATA', 'TECH_SIKIGAMI', 'TECH_ONIWABAN', 'TECH_HANGONNOGI', 'TECH_SUKIMA', 'TECH_BORDER_OF_LIFE'] ],
	['CIVILIZATION_ROME', ['TECH_HYOUSEIRENGOU', 'TECH_KURAYAMI', 'TECH_MUSINOSIRASE', 'TECH_MOUUTA', 'TECH_MARUKYU', 'TECH_LETTYJIRUSI', 'TECH_SIZENNOKYOUI'] ],
	['CIVILIZATION_EGYPT', ['TECH_EIENTEI', 'TECH_SUZURANNODOKU', 'TECH_INABANOSIROUSAGI', 'TECH_SINOOSIE', 'TECH_TUKINOZUNOU', 'TECH_NANATUNONANDAI', 'TECH_TUKIKARANOSISHA'] ],
	['CIVILIZATION_SPAIN', ['TECH_YOUKAINOYAMA', 'TECH_KAPPANOHATUMEI', 'TECH_TENGUNOJOUHOUMOU', 'TECH_ARAHITOGAMINOKISEKI', 'TECH_MISHAGUJISAMA', 'TECH_MOUNTAIN_OF_FAITH', 'TECH_MORIYANOOUKOKU'] ],
	['CIVILIZATION_JAPAN', ['TECH_HAKUREIJINJA', 'TECH_MAHOU', 'TECH_FURUDOUGUYA', 'TECH_NINGYOUSOUJUTU', 'TECH_HAKUREINODENTOU', 'TECH_HYAKUMANKIYAKOU', 'TECH_HAKUREIDAIKEKKAI'] ],
	['CIVILIZATION_PERSIA', ['TECH_CHIREIDEN', 'TECH_HASHIHIME', 'TECH_KAIRIKIRANSHIN', 'TECH_KAENPYO', 'TECH_KOKOROWOYOMUME', 'TECH_MUISHIKINOIDENSHI', 'TECH_CHITEINOTAIYOSHINKO'] ],
	['CIVILIZATION_RUSSIA', ['TECH_SEIRENSEN', 'TECH_TINY_CLEVER_COMMANDER', 'TECH_GUARDIAN_RING', 'TECH_FlYING_SHIP', 'TECH_UNDEFINED_FANTASTIC_OBJECT', 'TECH_BISHAMON_TIGER', 'TECH_TEACHING_OF_MEIREN'] ],
	['CIVILIZATION_CHINA', ['TECH_SHINREIBYOU', 'TECH_TYOKUREI', 'TECH_ZYASENNOHUKYOU', 'TECH_KANIZYUUNIKAI', 'TECH_SHIKAISEN', 'TECH_SEIZINNOHUKKATU', 'TECH_HOSIHURU_SHINREIBYOU'] ],
	['CIVILIZATION_MALI', ['TECH_KISHINJOU', 'TECH_JAKUSYANORAKUEN', 'TECH_USINAWARETA_SEISIN', 'TECH_GEKOKUJOU', 'TECH_SAIGONONOZOMI', 'TECH_KAISYUUKI', 'TECH_MUGENNOTIKARA'] ],
	['CIVILIZATION_AMERICA', ['TECH_TUKI_NO_MIYAKO', 'TECH_MOON_WAR_FIRST', 'TECH_APOLLO', 'TECH_APOLLO_CONSPIRACY', 'TECH_LUNAR_CAPITAL_TRANSFER_PLAN', 'TECH_SAKE_OF_THE_WATATSUKI', 'TECH_THE_TRUMP_CARD_IS_ALWAYS_A_BAD_MOVE', ] ],
	['CIVILIZATION_INDIA', ['TECH_KEINENOIRAI'] ],
]
